version: '3'
services:
  # nginx:
  #   image: "nginx:stable-alpine"
  #   ports:
  #     - "5173:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./src:/var/www
  react-app:
    build: .
    ports:
      - "5173:8000"
    volumes:
      - ./src:/app/src
